---
title: "ML_descriptive analysis"
author: "Soomin"
date: "August 19, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(VIM)
library(purrr)
library(tidyr)
library(ggplot2)
library(dplyr)
library(plyr)


train_dt = read.csv("C:/Users/jolie/Google Drive/04. Study/0. NYC Data Science/1. Projects/3. Machine Learning/data/train.csv")
test_dt = read.csv("C:/Users/jolie/Google Drive/04. Study/0. NYC Data Science/1. Projects/3. Machine Learning/data/test.csv")
full_dt = data.frame(rbind.fill(train_dt, test_dt))


View(full_dt)
dim(full_dt)
summary(full_dt)
num_na = sapply(full_dt, function(x) sum(is.na(x)))
full_dt %>%
  select(everything()) %>%  # replace to your needs
  summarise_all(funs(sum(is.na(.))))
num_na[num_na > 0]

# LotFrontage, Alley, (MasVnrType, MasVnrArea), 
# (BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinType2),
# Electrical, FireplaceQu, (GarageType, GarageFinish, GarageQual, GarageCond), 
# PoolQC, Fence, MiscFeature


aggr(full_dt)

library(mice)
md.pattern(full_dt)


### descriptive 
library(psych)
describe(full_dt)
full_dt %>% str()

numeric_dt = sapply(full_dt, function(x) is.numeric(x))
round(cor(full_dt[, sapply(full_dt, function(x) is.numeric(x))]), 2)
pairs.panels(full_dt[, 1:10])
sort(cor(x=train_dt %>% keep(is.numeric), y=train_dt$SalePrice)[,1])


full_dt %>%
  keep(is.numeric) %>% 
  gather() %>% 
  ggplot(aes(value)) +
  facet_wrap(~ key, scales = "free") +
  geom_histogram()

train_dt %>%
  keep(is.numeric) %>% 
  gather() %>% 
  ggplot(aes(value)) +
  facet_wrap(~ key, scales = "free") +
  geom_histogram()

sort(unique(train_dt$GarageYrBlt))
# only GarageYrBlt shows a huge difference in its distribution between train and test data. 
# --> the test data GarageYrBlt has '2207', which seems to be an error to be adjusted..

```

